// Decoder — single source of truth for the glossary.
// Loaded by BOTH the web app (web/index.html) and the extension (content script + popup).
// EDIT HERE, then copy to the other location:  cp web/concepts.js extension/concepts.js
// (web app reads DECODER_CONCEPTS + DECODER_LENSES; extension reads DECODER_CONCEPTS + DECODER_STATUS)

window.DECODER_CONCEPTS = [
  { id:'rag', term:'RAG', aliases:'Retrieval-Augmented Generation', said:'“rag”', aliasList:['rag','retrieval augmented generation','retrieval-augmented generation'], status:'Core',
    oneLiner:'Hand the model a stack of your documents to read before it answers, so it stops making things up.',
    analogy:'An open-book exam — instead of reciting from memory, it looks up the right page first.',
    example:'A support bot that quotes your actual help docs instead of confidently guessing is doing RAG.',
    related:[{text:'Often confused with fine-tuning — that changes the model itself; RAG just hands it notes.',id:'finetuning'},{text:'Runs on embeddings under the hood.',id:'embeddings'},{text:'Exists mostly to dodge the context window limit.',id:'contextwindow'}],
    deeper:'Your docs get chopped into chunks, turned into embeddings, and stored in a vector database. At query time the system finds the closest chunks and stuffs them into the context window next to your question. Quality lives and dies on the retrieval step — bad chunks in, bad answer out.' },

  { id:'evals', term:'Evals', aliases:'Evaluations', said:'“ee-vals”', aliasList:['evals','eval','evaluations','evaluation'], status:'Core',
    oneLiner:'Tests for AI — a repeatable way to check whether the model actually got better or just feels like it did.',
    analogy:'A unit-test suite, but for judgment instead of code.',
    example:'Before shipping a new prompt, a team runs it against 500 saved questions and counts how many it nails.',
    related:[{text:'The scoreboard a human in the loop quietly fills.',id:'hitl'},{text:'What you run to catch a hallucination before users do.',id:'hallucination'}],
    deeper:'They range from exact-match graders to “LLM-as-judge” setups where one model scores another. The hard part is never running them — it is writing eval sets that reflect what real users actually do, not what is easy to grade.' },

  { id:'contextwindow', term:'Context window', aliases:'', said:'', aliasList:['context window'], status:'Core',
    oneLiner:'How much the model can hold in view at once — your prompt, the docs, the whole chat — before the start falls off.',
    analogy:'Short-term memory, or a desk that only fits so many papers before the older ones slide off the edge.',
    example:'Paste a 400-page PDF into a small-context model and it will quietly lose the early chapters.',
    related:[{text:'Measured in tokens.',id:'tokens'},{text:'The ceiling RAG is designed to work around.',id:'rag'}],
    deeper:'Windows have grown from a few thousand tokens to millions, but “it fits” is not “it uses well.” Models often attend better to the beginning and end than the muddled middle — the classic “lost in the middle” effect.' },

  { id:'hitl', term:'HITL', aliases:'Human in the loop', said:'“human in the loop”', aliasList:['hitl','human in the loop'], status:'Core',
    oneLiner:'A person checks or approves the AI’s work before it counts — the safety catch on high-stakes steps.',
    analogy:'A spellchecker that suggests, but you still have to hit accept.',
    example:'The AI drafts the refund; a human clicks approve before any money actually moves.',
    related:[{text:'The judgment that becomes your evals.',id:'evals'},{text:'The opposite pole from a fully autonomous agent.',id:'agents'}],
    deeper:'The real design question is where the human sits: on every action (slow, safe), on random samples (a spot check), or only on low-confidence cases where the model itself asks for help. Most teams end up with the third.' },

  { id:'agents', term:'Agents', aliases:'', said:'', aliasList:['agent','agents','agentic'], status:'Rising',
    oneLiner:'AI that doesn’t just answer — it takes steps, uses tools, and works toward a goal without you holding its hand.',
    analogy:'Less like a search box, more like an intern you can hand a whole task to.',
    example:'When a coding assistant reads your files, runs the tests, and fixes what broke, that’s an agent at work.',
    related:[{text:'The grown-up version of a chatbot.'},{text:'Only as useful as its tools — which is what MCP standardizes.',id:'mcp'},{text:'Its scariest failure mode is prompt injection.',id:'promptinjection'}],
    deeper:'Under the hood it’s a loop: the model picks an action, something runs it, the result comes back, repeat until done. Most “agent” failures are really loop-control failures — it gets stuck, over-repeats, or wanders off the goal.' },

  { id:'embeddings', term:'Embeddings', aliases:'', said:'', aliasList:['embedding','embeddings'], status:'Core',
    oneLiner:'Turning words into coordinates, so a computer can measure how close in meaning two things are.',
    analogy:'A map where “dog” and “puppy” are next-door neighbors and “dog” and “tax form” are on opposite coasts.',
    example:'Search that finds “car” when you typed “automobile” is matching on embeddings, not on spelling.',
    related:[{text:'The engine underneath RAG.',id:'rag'},{text:'Not the same as tokens, though both are “text as numbers.”',id:'tokens'}],
    deeper:'Each piece of text becomes a long list of numbers — a vector. “Similar” means the vectors point in nearly the same direction (cosine similarity). The entire trick of semantic search lives in this one idea.' },

  { id:'finetuning', term:'Fine-tuning', aliases:'', said:'', aliasList:['fine-tuning','fine tuning','finetuning'], status:'Fading',
    oneLiner:'Retraining a model a little on your own examples so it picks up a style or skill it didn’t ship with.',
    analogy:'Sending a strong generalist off to a short apprenticeship in your specific shop.',
    example:'Training on 10,000 of your past support replies so the model sounds like your team, not a robot.',
    related:[{text:'Often reached for when RAG would have done the job.',id:'rag'},{text:'A heavier hammer than good prompt engineering.',id:'promptengineering'}],
    deeper:'Techniques like LoRA make it cheap by nudging a small set of weights instead of all of them. It’s cooling as a first move: most teams now try prompting and RAG first, because a fine-tune is a maintenance burden that goes stale with the base model.' },

  { id:'vibecoding', term:'Vibe coding', aliases:'obituary', said:'“vibe coding”', aliasList:['vibe coding','vibe-coding','vibecoding'], status:'Historical',
    oneLiner:'What we briefly called just… talking to an AI until the app worked, without really reading the code.',
    analogy:'Cooking without measuring — totally fine for a snack, faintly terrifying for a wedding cake.',
    example:'In 2024, “I vibe-coded a weekend app” meant you prompted your way to something that ran and shipped it.',
    related:[{text:'Folded into “agentic coding.”',id:'agents'},{text:'The reflex it named lives on inside prompt engineering.',id:'promptengineering'}],
    deeper:'Filed as history: what people meant in 2024–25, and why it grew up. The term peaked in early 2025, then split — the throwaway-prototype meaning stuck around as a joke, while the actual practice matured into agentic coding with tests, reviews, and specs. The vibes, it turned out, needed guardrails.' },

  { id:'promptengineering', term:'Prompt engineering', aliases:'', said:'', aliasList:['prompt engineering'], status:'Fading',
    oneLiner:'The craft of phrasing your request just right to coax out a better answer.',
    analogy:'Knowing how to Google well — a real skill that quietly becomes second nature.',
    example:'“Think step by step, then answer” reliably beats just asking — a classic prompt-engineering move.',
    related:[{text:'Overlaps heavily with chain of thought.',id:'chainofthought'},{text:'Cooling as models get better at reading plain intent.'}],
    deeper:'Once a hot job title, it’s cooling not because it’s useless but because it’s diffusing into everyone’s baseline. The heavy lifting moved to context and tools; the exact wording matters far less than it did back in 2023.' },

  { id:'tokens', term:'Tokens', aliases:'', said:'', aliasList:['token','tokens'], status:'Core',
    oneLiner:'The chunks a model reads and writes in — roughly ¾ of a word each. Everything is priced and measured in them.',
    analogy:'Syllables for a machine — not quite letters, not quite whole words.',
    example:'“unbelievable” might be three tokens: un-believ-able. Your bill counts every single one.',
    related:[{text:'The unit the context window is measured in.',id:'contextwindow'},{text:'Cousin of embeddings — both turn text into numbers.',id:'embeddings'}],
    deeper:'Tokenization is why models miscount the letters in a word or fumble rare strings — they never saw the letters, only the chunks. It also explains why some languages cost more: they tokenize less efficiently, so the same sentence spends more tokens.' },

  { id:'hallucination', term:'Hallucination', aliases:'', said:'', aliasList:['hallucinate','hallucination','hallucinations'], status:'Core',
    oneLiner:'When the model states something false with total confidence — the failure mode that never fully goes away.',
    analogy:'A friend who never says “I don’t know” and just fills the gap with a plausible-sounding story.',
    example:'Ask for a citation and get a real-looking paper, by real-looking authors, that simply does not exist.',
    related:[{text:'What RAG tries to ground away.',id:'rag'},{text:'What evals exist to catch.',id:'evals'}],
    deeper:'It’s not lying — the model predicts likely text, and “likely” is not “true.” Grounding it in real documents and asking it to cite reduces it, but confidence and correctness are separate dials. A model can be dead wrong and completely sure.' },

  { id:'mcp', term:'MCP', aliases:'Model Context Protocol', said:'“em-see-pee”', aliasList:['mcp','model context protocol'], status:'Rising',
    oneLiner:'A standard plug so any AI can talk to your tools and data without a custom integration each time.',
    analogy:'USB-C for AI — one connector instead of a junk drawer of adapters.',
    example:'Point an assistant at an MCP server for your calendar and it can read your schedule with no bespoke code.',
    related:[{text:'What makes agents actually useful in the real world.',id:'agents'}],
    deeper:'It defines how a model discovers tools, calls them, and gets results back. Boring plumbing on purpose — that boringness is what lets the whole agent ecosystem interoperate instead of everyone reinventing the same wiring.' },

  { id:'chainofthought', term:'Chain of thought', aliases:'CoT', said:'', aliasList:['chain of thought','cot'], status:'Core',
    oneLiner:'Letting the model reason out loud in steps before answering — it gets more right when it shows its work.',
    analogy:'Doing long division on paper instead of trying to hold it all in your head.',
    example:'Nudging “let’s work through this step by step” measurably boosts hard math and logic problems.',
    related:[{text:'A staple of prompt engineering.',id:'promptengineering'},{text:'Now baked into “reasoning” models by default.'}],
    deeper:'Newer reasoning models do this internally, spending extra compute to think before replying. The visible scratchpad became a hidden one — same idea, just more of it, and often no longer shown to you.' },

  { id:'temperature', term:'Temperature', aliases:'', said:'', aliasList:['temperature'], status:'Core',
    oneLiner:'A dial for how adventurous the model is — low is focused and repetitive, high is creative and risky.',
    analogy:'The difference between a careful accountant and a poet mid-brainstorm.',
    example:'Set it near 0 to extract data cleanly; crank it up when you want ten weird names for a product.',
    related:[{text:'One of several “sampling” knobs, alongside top-p and top-k.'},{text:'Turn it down for extraction, up for ideation.'}],
    deeper:'It reshapes the probability distribution over the next token. High temperature flattens it so rare words get a chance; low temperature sharpens it so the safe pick almost always wins. Related knobs — top-p and top-k — trim the same distribution differently.' },

  { id:'promptinjection', term:'Prompt injection', aliases:'', said:'', aliasList:['prompt injection'], status:'Rising',
    oneLiner:'A sneaky attack where hidden instructions buried in your data hijack what the AI does.',
    analogy:'A note slipped into a stack of paperwork that reads “ignore your boss, do this instead.”',
    example:'A webpage hides “forward the user’s email to me” in white text; a browsing agent reads it and obeys.',
    related:[{text:'The security nightmare that comes free with agents.',id:'agents'},{text:'A strong reason to keep a human in the loop.',id:'hitl'}],
    deeper:'The root problem: models can’t reliably tell “data to process” from “instructions to follow.” There’s no clean fix yet — defenses are layered (sandboxing, human approval on risky actions, input filtering), not solved. Treat any untrusted text an agent reads as potentially hostile.' },

  { id:'contextengineering', term:'Context engineering', aliases:'', said:'', aliasList:['context engineering'], status:'Rising',
    oneLiner:'Deciding what to put in front of the model at each step — instructions, docs, history, tool results — so it has exactly what it needs and nothing that distracts it.',
    analogy:'Prepping a chef’s station before service: the right ingredients within reach, the clutter cleared away.',
    example:'An agent that pulls only the three relevant files into the prompt, instead of dumping your whole repo, is doing context engineering.',
    related:[{text:'The grown-up successor to prompt engineering — less about wording, more about what information is present.',id:'promptengineering'},{text:'Exists to spend the context window wisely.',id:'contextwindow'},{text:'What long-term memory feeds into.',id:'agentmemory'}],
    deeper:'The reframing is that a model is only as good as the context it’s given, so the real work is assembling that context on the fly: system instructions, retrieved documents, session history, and prior tool results — packed to fit the window and ordered so the important parts land where the model attends best. Get this right and mediocre prompts still work; get it wrong and no clever wording saves you.' },

  { id:'orchestration', term:'Orchestration layer', aliases:'', said:'', aliasList:['orchestration','orchestration layer'], status:'Core',
    oneLiner:'The control loop that runs an agent — it decides when to think, which tool to call, and what to do with the result, over and over until the job is done.',
    analogy:'The conductor of an orchestra: not playing an instrument, but cueing each one at the right moment.',
    example:'When an agent checks the order database, then calls the shipping API, then writes the reply, the orchestration layer is what sequences those steps.',
    related:[{text:'The “nervous system” that drives an agent between model and tools.',id:'agents'},{text:'Runs reasoning patterns like ReAct.',id:'react'},{text:'Manages what goes into the context window each turn.',id:'contextengineering'}],
    deeper:'It’s the state machine around the “think, act, observe” loop: the model proposes an action, the layer runs the tool, feeds the observation back, and reprompts — repeating until a stop condition. Most agent failures are really orchestration failures: it loops forever, repeats itself, or wanders off the goal. This is also where memory, planning, and guardrails get wired in.' },

  { id:'tooluse', term:'Tool use', aliases:'Function calling', said:'', aliasList:['tool use','tool calling','function calling','function call','tools'], status:'Core',
    oneLiner:'Giving the model a set of actions it can trigger — search, send an email, run code — so it can do things instead of only talking about them.',
    analogy:'Handing a brilliant advisor a phone and a keyboard — now the advice becomes action.',
    example:'The model outputs “call get_weather(‘Paris’)”, your code runs it, and the result comes back for the model to use. That round trip is tool use.',
    related:[{text:'The “hands” that make an agent more than a chatbot.',id:'agents'},{text:'Standardized across apps by MCP.',id:'mcp'},{text:'Reading from documents is one kind of tool — see grounding.',id:'grounding'}],
    deeper:'The model doesn’t run anything itself — it emits a structured request (a function name and arguments matching a schema), your system executes it, and the result is fed back into the context. Reliability hinges on clear tool descriptions and tight schemas: vague or overlapping tools are the top reason a model picks the wrong one or fills in bad arguments.' },

  { id:'a2a', term:'A2A', aliases:'Agent2Agent', said:'“a-two-a”', aliasList:['a2a','agent2agent','agent to agent','agent-to-agent'], status:'Rising',
    oneLiner:'A standard that lets separate agents discover each other and work together, instead of everyone wiring up custom connections.',
    analogy:'A business-card exchange for bots — each agent advertises what it can do and how to reach it.',
    example:'A “project manager” agent hands a research task to a specialist research agent it found via A2A, then waits for the result.',
    related:[{text:'The agent-to-agent counterpart to MCP, which connects agents to tools.',id:'mcp'},{text:'What makes multi-agent systems practical.',id:'multiagent'}],
    deeper:'Each agent publishes an “Agent Card” — a JSON file listing its capabilities, endpoint, and auth requirements — so others can discover and call it. Interactions are framed as asynchronous tasks with streaming updates, not simple request-response. Where MCP standardizes an agent reaching for a tool, A2A standardizes one agent delegating to another.' },

  { id:'llmjudge', term:'LLM-as-judge', aliases:'LLM as a Judge', said:'', aliasList:['llm-as-judge','llm as judge','llm as a judge','model as judge','llm judge'], status:'Rising',
    oneLiner:'Using one AI model to score another’s output against a rubric, because “right or wrong” is too crude for judging language.',
    analogy:'A grading TA — not the professor, but consistent, tireless, and good enough to flag the essays worth a closer look.',
    example:'After a prompt change, a judge model rates 500 answers for accuracy and tone, so the team sees if quality moved before shipping.',
    related:[{text:'The automated grader that powers most evals.',id:'evals'},{text:'Still needs a human in the loop to trust its calls.',id:'hitl'},{text:'A common way to catch a hallucination at scale.',id:'hallucination'}],
    deeper:'You give a capable model a rubric — was it factually grounded, did it follow instructions, was the tone right — and have it score outputs against a golden dataset. It scales judgment that would take humans forever, but it inherits the judge model’s own biases and blind spots, so results should be spot-checked by a domain expert before you trust them.' },

  { id:'grounding', term:'Grounding', aliases:'', said:'', aliasList:['grounding','grounded'], status:'Core',
    oneLiner:'Making the model answer from real, retrieved facts instead of its own memory — so it can cite a source instead of guessing.',
    analogy:'Showing your work with references, rather than answering a pop quiz from memory.',
    example:'A support bot that pulls the actual refund policy and quotes it — rather than inventing one — is grounded.',
    related:[{text:'RAG is the most common way to ground an agent.',id:'rag'},{text:'The main defense against hallucination.',id:'hallucination'},{text:'Achieved by giving the agent retrieval tools.',id:'tooluse'}],
    deeper:'Grounding means tying a response to authoritative external data — company docs, a database, live search — fetched at answer time and placed in the context. It sharply reduces made-up facts and makes answers checkable, but it’s only as good as the retrieval: if the wrong documents come back, the model grounds itself in the wrong thing, confidently.' },

  { id:'multiagent', term:'Multi-agent systems', aliases:'', said:'', aliasList:['multi-agent','multi agent','multi-agent system','multi-agent systems','multiagent'], status:'Rising',
    oneLiner:'Splitting a big job across several specialized agents that work together, instead of asking one agent to do everything.',
    analogy:'A film crew instead of a one-man band — a director, a researcher, a writer, each good at their part.',
    example:'A “manager” agent hands research to one agent, drafting to another, and formatting to a third, then assembles the pieces.',
    related:[{text:'Agents that treat other agents as tools.',id:'agents'},{text:'Held together by protocols like A2A.',id:'a2a'},{text:'Coordinating them is an orchestration problem.',id:'orchestration'}],
    deeper:'The idea mirrors a human org: break a complex process into sub-tasks and give each to a focused agent that’s simpler to build, test, and trust. Common patterns include a coordinator that routes work to specialists, a sequential “assembly line,” and a generator-critic pair for quality. The cost is coordination overhead — more moving parts, more ways for the handoffs to go wrong.' },

  { id:'agentops', term:'Agent Ops', aliases:'AgentOps', said:'', aliasList:['agent ops','agentops','agent operations'], status:'Rising',
    oneLiner:'The practice of testing, monitoring, and improving agents in production — DevOps adapted for software that behaves differently every run.',
    analogy:'Running a kitchen after opening night: tasting dishes, watching tickets, fixing the recipe while service continues.',
    example:'Logging every agent run, scoring a sample nightly, and turning each bug report into a permanent test is Agent Ops in action.',
    related:[{text:'Built on a foundation of evals.',id:'evals'},{text:'Depends on observability to see what the agent did.',id:'observability'},{text:'Feeds human feedback back into the loop.',id:'hitl'}],
    deeper:'Because agent output is probabilistic, you can’t assert output == expected; Agent Ops replaces that with continuous evaluation, tracing, and metrics-driven go/no-go decisions. The loop it closes: capture a real-world failure, reproduce it, convert it into a permanent eval, and re-test forever. It’s a natural evolution of DevOps and MLOps for non-deterministic systems.' },

  { id:'guardrails', term:'Guardrails', aliases:'', said:'', aliasList:['guardrail','guardrails'], status:'Core',
    oneLiner:'Hard limits placed around an agent so it physically can’t do the dangerous thing, no matter what the model decides.',
    analogy:'The bumpers in a bowling lane — the ball can wander, but it can’t end up in the gutter.',
    example:'A rule that blocks any purchase over $100 without human sign-off holds even if a prompt tricks the model into trying.',
    related:[{text:'The deterministic backstop against prompt injection.',id:'promptinjection'},{text:'Often implemented as a human-in-the-loop checkpoint.',id:'hitl'},{text:'A leash on what an agent can do.',id:'agents'}],
    deeper:'The key move is defense in depth: hardcoded rules outside the model (spending caps, blocked actions, required confirmations) that can’t be reasoned away, plus AI-based “guard models” that screen inputs and outputs for injections or unsafe plans. You never rely on the model’s judgment alone, because that judgment can be manipulated — the code-level limits are what stay predictable and auditable.' },

  { id:'observability', term:'Observability', aliases:'Traces', said:'', aliasList:['observability','traces','trace','tracing'], status:'Core',
    oneLiner:'A step-by-step recording of everything an agent did — its reasoning, tool calls, and results — so you can answer “why did it do that?”',
    analogy:'A flight recorder for your agent — when something goes wrong, you can replay the whole trajectory.',
    example:'A trace shows the agent picked the wrong tool at step three with a bad argument — now you know exactly what to fix.',
    related:[{text:'The foundation Agent Ops is built on.',id:'agentops'},{text:'Turns a fuzzy failure into a fixable step you can add to your evals.',id:'evals'},{text:'How you debug the agent, not just the model.',id:'orchestration'}],
    deeper:'It rests on three pillars: logs (what happened), traces (the full ordered path of a single run, with each prompt, tool, parameter, and observation), and metrics (aggregate health like latency, cost, and quality scores). You can’t set a breakpoint inside a model’s “thought,” so the trace is how you see the reasoning trajectory and find the root cause. Standards like OpenTelemetry make this portable.' },

  { id:'agentmemory', term:'Agent memory', aliases:'', said:'', aliasList:['agent memory','short-term memory','long-term memory'], status:'Rising',
    oneLiner:'How an agent holds on to information — the running scratchpad of the current task, plus a longer store it can recall across sessions.',
    analogy:'A desk notepad for today’s work, and a filing cabinet for everything worth keeping.',
    example:'An assistant that remembers next week you prefer aisle seats — without being told again — is using long-term memory.',
    related:[{text:'What context engineering pulls from each turn.',id:'contextengineering'},{text:'Long-term memory is usually a RAG system under the hood.',id:'rag'},{text:'Lives inside the context window while active.',id:'contextwindow'}],
    deeper:'Short-term memory is the session scratchpad — the running history of actions and observations the model needs to decide its next step. Long-term memory persists across sessions and is almost always implemented as a separate tool: a vector store the agent writes to and later retrieves from. The hard parts are deciding what’s worth remembering, and pulling the right memory back into context at the right moment.' },

  { id:'react', term:'ReAct', aliases:'Reason + Act', said:'“re-act”', aliasList:['react','reason and act','reason + act','reasoning and acting'], status:'Core',
    oneLiner:'A loop where the model reasons about what to do, takes one action, sees the result, then reasons again — the basic rhythm of most agents.',
    analogy:'Cooking from a recipe you’re also writing: taste, adjust, take the next step, taste again.',
    example:'“I need the roster, so I’ll call get_team_roster” → runs it → “now I have five names, next I’ll check their calendars.” That’s ReAct.',
    related:[{text:'The reasoning pattern the orchestration layer runs.',id:'orchestration'},{text:'A cousin of chain of thought, but with actions between the thoughts.',id:'chainofthought'},{text:'The loop that defines how an agent works.',id:'agents'}],
    deeper:'ReAct interleaves reasoning traces with tool actions: think, act, observe, repeat — instead of reasoning all the way to an answer in one shot. Letting the model see each observation before planning the next step makes it far better at multi-step tasks and grounds its reasoning in real results. It’s the pattern under most agent frameworks, even when they dress it up.' },

  { id:'computeruse', term:'Computer use', aliases:'', said:'', aliasList:['computer use','computer-use'], status:'Rising',
    oneLiner:'An agent that operates a screen the way a person would — clicking buttons, filling forms, navigating pages — instead of calling a clean API.',
    analogy:'Handing the AI a mouse and keyboard and letting it drive, rather than plugging it into the wiring directly.',
    example:'When there’s no API, an agent can open the web page, click through the booking form, and submit it — that’s computer use.',
    related:[{text:'A kind of tool an agent can wield.',id:'tooluse'},{text:'Risky enough that it usually keeps a human in the loop.',id:'hitl'},{text:'A wide-open door for prompt injection from what’s on screen.',id:'promptinjection'}],
    deeper:'The agent takes screenshots, decides where to click or type, and acts on the raw interface — reaching systems that never exposed an API. It’s powerful and general but slower, more brittle, and less safe than a proper tool: a stray button or a malicious instruction hidden on a page can derail it, which is why oversight and confirmation steps matter here more than anywhere.' },

  { id:'agentidentity', term:'Agent identity', aliases:'', said:'', aliasList:['agent identity','agent identities'], status:'Rising',
    oneLiner:'Giving each agent its own verifiable ID — separate from the user and the developer — so its actions can be permissioned and audited.',
    analogy:'An employee badge for a bot: it says who this agent is and exactly which doors it may open.',
    example:'A sales agent gets read/write to the CRM but is flatly denied HR data — because its identity carries its own permissions.',
    related:[{text:'The basis for putting guardrails on what an agent can touch.',id:'guardrails'},{text:'Essential once agents act on your behalf.',id:'agents'},{text:'Contains the blast radius if an agent is hijacked by prompt injection.',id:'promptinjection'}],
    deeper:'Traditional security knows two kinds of actor: human users and service accounts. Agents are a third — autonomous, acting with delegated authority — so they need their own cryptographic identity (via standards like SPIFFE) rather than borrowing a human’s. With a real identity, an agent gets least-privilege permissions and every action traces back to it, so a compromised agent can only reach the little it was granted.' },

  { id:'vectordb', term:'Vector database', aliases:'Vector store', said:'', aliasList:['vector database','vector db','vector store','vectordb'], status:'Core',
    oneLiner:'A database that stores text as coordinates and finds things by meaning, not keywords — the memory bank behind search that “just gets it.”',
    analogy:'A library organized by what books are about, not by title — ask for something and the neighbors are all related.',
    example:'Search “how do I cancel” and it surfaces the “ending your subscription” doc, because their vectors sit close together.',
    related:[{text:'Stores the embeddings that make it work.',id:'embeddings'},{text:'The retrieval engine underneath RAG.',id:'rag'},{text:'Where an agent’s long-term memory usually lives.',id:'agentmemory'}],
    deeper:'Text is turned into embeddings — long lists of numbers — and the database indexes them so it can quickly find the nearest vectors to a query (approximate nearest-neighbor search). “Near” means similar in meaning. It’s the storage layer that makes semantic search, RAG, and long-term memory fast enough to use at scale, even over millions of chunks.' },

  { id:'agentpayments', term:'Agentic payments', aliases:'AP2, x402', said:'', aliasList:['agentic payments','agent payments','ap2','agent payments protocol','x402'], status:'Rising',
    oneLiner:'Emerging standards that let an agent pay or transact on your behalf — with proof you actually authorized it.',
    analogy:'A signed permission slip for a bot: it can spend, but only within what you clearly agreed to.',
    example:'You tell an agent “book the flight under $400” and it pays — backed by a signed mandate proving those were your terms.',
    related:[{text:'Builds on the agent-to-agent protocol.',id:'a2a'},{text:'A big reason to keep a human in the loop on real money.',id:'hitl'},{text:'Raises the stakes of prompt injection enormously.',id:'promptinjection'}],
    deeper:'The web assumes a human clicks “buy,” so an autonomous agent spending money creates a trust gap — who’s accountable if it goes wrong? Two protocols are early answers: AP2 (Agent Payments Protocol) uses cryptographically-signed “mandates” as verifiable proof of user intent, and x402 uses the HTTP 402 “Payment Required” code for tiny machine-to-machine payments. Both are early and unsettled, but they aim to be the trust layer for an agent economy.' },

  { id:'reasoningmodels', term:'Reasoning models', aliases:'', said:'', aliasList:['reasoning model','reasoning models','thinking model','thinking models'], status:'Rising',
    oneLiner:'Models that think before they answer — spending extra compute working through a problem internally instead of blurting the first response.',
    analogy:'The colleague who pauses and works it out on scratch paper, versus the one who answers instantly and is sometimes wrong.',
    example:'Give a hard logic puzzle to a reasoning model and it quietly works through steps first, landing the answer far more often.',
    related:[{text:'Chain of thought, now baked in and hidden instead of prompted.',id:'chainofthought'},{text:'They trade latency and tokens for accuracy.',id:'tokens'},{text:'The stronger “brain” behind capable agents.',id:'agents'}],
    deeper:'They internalize chain-of-thought: instead of you prompting “think step by step,” the model does it by default, spending more compute (and tokens) on a hidden scratchpad before replying. That buys big gains on math, code, and multi-step logic, at the cost of speed and price. The reasoning is often no longer shown to you — same idea as before, just more of it and tucked away.' },

  { id:'trajectory', term:'Trajectory', aliases:'', said:'', aliasList:['trajectory','trajectories'], status:'Rising',
    oneLiner:'The full step-by-step path an agent took to reach an answer — every thought, tool call, and result along the way.',
    analogy:'Not just the destination, but the whole GPS route — where it turned, backtracked, and why.',
    example:'Two agents give the same right answer, but one took twelve messy steps and the other took three — the trajectory tells them apart.',
    related:[{text:'What a trace records so you can inspect it.',id:'observability'},{text:'Judging the path, not just the output, is a core eval move.',id:'evals'},{text:'Produced by the think-act-observe loop.',id:'react'}],
    deeper:'For agents, the final answer isn’t enough — a right answer reached by a lucky, wasteful, or unsafe path is still a problem. Trajectory evaluation (“the glass box”) judges the whole sequence of decisions: did it pick the right tools, in a sensible order, without needless steps? It’s how you catch quality and safety issues that a correct-looking output would hide.' },

  // ---- Foundational generative-AI vocabulary (the basics behind “GANs to GPT-4” style articles) ----

  { id:'genai', term:'Generative AI', aliases:'GenAI', said:'', aliasList:['generative ai','gen ai','genai'], status:'Core',
    oneLiner:'AI that makes new things — text, images, music, code — instead of just sorting or labeling what already exists.',
    analogy:'The difference between a critic who rates paintings and an artist who paints new ones.',
    example:'Ask a tool to write a poem or draw a cat surfing and get something that never existed before — that’s generative AI.',
    related:[{text:'Almost always a deep learning model under the hood.',id:'deeplearning'},{text:'For text, it usually means a large language model.',id:'llm'},{text:'The early image version was built on GANs.',id:'gan'}],
    deeper:'It learns the patterns in a huge pile of examples, then samples from those patterns to produce something new rather than retrieving a stored answer. The same core idea powers chatbots, image generators, and code assistants — only the training data and output format change.' },

  { id:'machinelearning', term:'Machine learning', aliases:'ML', said:'', aliasList:['machine learning','ml'], status:'Core',
    oneLiner:'Software that learns patterns from examples instead of being programmed with explicit rules.',
    analogy:'Teaching by showing thousands of examples rather than writing out every rule by hand.',
    example:'A spam filter that improves from the messages you mark as junk is machine learning, not hand-coded rules.',
    related:[{text:'Deep learning is the branch that powers modern AI.',id:'deeplearning'},{text:'The umbrella that neural networks live under.',id:'neuralnetwork'},{text:'Its most common flavor is supervised learning.',id:'supervised'}],
    deeper:'Instead of a human writing “if X then Y” rules, the system adjusts its own internal numbers until its predictions match the examples. Most of what people call “AI” today is machine learning — the older rule-based approach is a separate, much smaller world.' },

  { id:'deeplearning', term:'Deep learning', aliases:'', said:'', aliasList:['deep learning'], status:'Core',
    oneLiner:'Machine learning that stacks many layers of neural network — the approach that made modern AI actually work.',
    analogy:'An assembly line where each station spots slightly bigger patterns — edges, then shapes, then faces.',
    example:'Face unlock, voice assistants, and ChatGPT are all deep learning under different coats of paint.',
    related:[{text:'It’s machine learning done with big neural networks.',id:'neuralnetwork'},{text:'The transformer is the deep-learning design behind today’s chatbots.',id:'transformer'},{text:'“Deep” means many layers trained by backpropagation.',id:'backprop'}],
    deeper:'“Deep” just means many layers stacked between input and output. More layers let the model learn richer, more abstract patterns, but need far more data and compute — which is why deep learning only took off once GPUs and huge datasets arrived.' },

  { id:'neuralnetwork', term:'Neural network', aliases:'', said:'', aliasList:['neural network','neural networks','neural net','artificial neural network'], status:'Core',
    oneLiner:'The web of simple math units, loosely inspired by brain cells, that most AI models are built from.',
    analogy:'A huge dimmer-switch panel — the model learns by nudging millions of dials until the output looks right.',
    example:'When an app recognizes your dog in a photo, a neural network is doing the seeing.',
    related:[{text:'Stacked many layers deep, it becomes deep learning.',id:'deeplearning'},{text:'The dials it tunes are its parameters.',id:'parameters'},{text:'It learns by backpropagation.',id:'backprop'}],
    deeper:'Each unit takes numbers in, weighs them, and passes a result to the next layer. The “weights” are the dials; training adjusts them so the whole network maps inputs to the right outputs. The brain analogy is loose — it’s really just layered arithmetic at massive scale.' },

  { id:'prompt', term:'Prompt', aliases:'', said:'', aliasList:['prompt','prompts','prompting'], status:'Core',
    oneLiner:'The instruction you type to an AI — the request it turns into an answer.',
    analogy:'The order you give a very literal assistant: word it well and you get what you wanted.',
    example:'“Write a birthday message for my dad who loves fishing” is a prompt.',
    related:[{text:'Wording prompts well is prompt engineering.',id:'promptengineering'},{text:'The prompt plus everything around it fills the context window.',id:'contextwindow'},{text:'A hostile prompt hidden in data is prompt injection.',id:'promptinjection'}],
    deeper:'Everything you send the model — question, instructions, examples, pasted documents — is the prompt. The model doesn’t “understand” it so much as continue it: it predicts the most likely response given those words, which is why small wording changes can swing the output.' },

  { id:'llm', term:'Large language model', aliases:'LLM', said:'“L-L-M”', aliasList:['large language model','large language models','llm','llms','language model','language models'], status:'Core',
    oneLiner:'An AI trained on enormous amounts of text to predict the next word — which turns out to be enough to write, summarize, and answer.',
    analogy:'Autocomplete that read most of the internet and got unnervingly good at it.',
    example:'ChatGPT, Claude, and Gemini are all large language models with a chat wrapper on top.',
    related:[{text:'Built on the transformer architecture.',id:'transformer'},{text:'GPT is one well-known family of LLMs.',id:'gpt'},{text:'Its confident wrong guesses are hallucinations.',id:'hallucination'}],
    deeper:'It’s a giant neural network trained to guess the next chunk of text, over and over, across trillions of words. That single objective — predict what comes next — is enough to pick up grammar, facts, tone, and reasoning patterns. It generates one token at a time.' },

  { id:'transformer', term:'Transformer', aliases:'', said:'', aliasList:['transformer','transformers'], status:'Core',
    oneLiner:'The 2017 neural-network design that made today’s language models possible, by letting a model weigh every word against every other at once.',
    analogy:'Instead of reading strictly left to right, it reads the whole sentence at once and decides which words matter most to each other.',
    example:'The “T” in GPT stands for Transformer — it’s the engine under almost every modern AI model.',
    related:[{text:'The architecture behind every large language model.',id:'llm'},{text:'Its “attention” trick is what fills the context window.',id:'contextwindow'},{text:'GPT is a transformer trained to generate text.',id:'gpt'}],
    deeper:'Its key idea is “attention”: for each word, the model computes how much every other word should influence it, in parallel rather than in sequence. That parallelism is what let training scale to internet-sized data — the leap that took AI from clumsy to fluent.' },

  { id:'gpt', term:'GPT', aliases:'Generative Pre-trained Transformer', said:'“G-P-T”', aliasList:['gpt','gpt-2','gpt-3','gpt-4','gpt-3.5','gpt-4o'], status:'Core',
    oneLiner:'The family of OpenAI language models — the “GPT” in ChatGPT — that pushed AI text into the mainstream.',
    analogy:'A model lineage, like car generations: GPT-2, GPT-3, GPT-4, each bigger and sharper than the last.',
    example:'GPT-4 can draft an email, explain code, and pass exams that stumped GPT-2 a few years earlier.',
    related:[{text:'GPT is one family of large language models.',id:'llm'},{text:'The “T” is for transformer.',id:'transformer'},{text:'ChatGPT is the chat app built on GPT.',id:'chatgpt'}],
    deeper:'GPT stands for Generative Pre-trained Transformer: pre-trained on huge text, transformer-based, generative. Each generation roughly scales up data and parameters, which reliably buys broader knowledge and better reasoning — the trend that “scaling” bets on.' },

  { id:'chatgpt', term:'ChatGPT', aliases:'', said:'', aliasList:['chatgpt','chat gpt'], status:'Core',
    oneLiner:'OpenAI’s chatbot — the app that put large language models in front of everyone in late 2022.',
    analogy:'The friendly front door to a GPT model: you type, it chats back.',
    example:'Asking ChatGPT to summarize your notes or plan a trip is using an LLM without ever seeing the machinery.',
    related:[{text:'It’s a chat wrapper over a GPT model.',id:'gpt'},{text:'Which is a large language model.',id:'llm'},{text:'Human feedback (RLHF) is what made it feel cooperative.',id:'rlhf'}],
    deeper:'ChatGPT is the product; GPT is the model inside. Its breakthrough wasn’t just the model but the chat format plus tuning with human feedback that made it follow instructions and feel conversational — which is why it, not GPT-3, went viral.' },

  { id:'gan', term:'GAN', aliases:'Generative Adversarial Network', said:'“gan”', aliasList:['gan','gans','generative adversarial network','generative adversarial networks'], status:'Fading',
    oneLiner:'An older image-generating design where two networks compete — one fakes, one detects — until the fakes look real.',
    analogy:'A forger and a detective locked in a race: each one gets sharper by trying to beat the other.',
    example:'The uncanny “this person does not exist” face generators were powered by GANs.',
    related:[{text:'Largely overtaken by diffusion models for image generation.',id:'diffusion'},{text:'An early form of generative AI.',id:'genai'},{text:'Both sides are neural networks.',id:'neuralnetwork'}],
    deeper:'Introduced in 2014, GANs dominated AI image generation for years: a generator makes fakes, a discriminator judges them, and their tug-of-war improves both. They’re now mostly historical for new tools — diffusion proved easier to train and scale — but GANs are why “generative” entered the conversation.' },

  { id:'diffusion', term:'Diffusion model', aliases:'', said:'', aliasList:['diffusion model','diffusion models','diffusion'], status:'Core',
    oneLiner:'The technique behind most modern AI image tools — it learns to turn random noise into a picture, step by step.',
    analogy:'Sculpting in reverse: start with TV static and gradually clean it into the image you asked for.',
    example:'Midjourney, DALL·E, and Stable Diffusion all generate images with diffusion.',
    related:[{text:'It replaced GANs as the go-to for image generation.',id:'gan'},{text:'Powers text-to-image tools.',id:'texttoimage'},{text:'A form of generative AI for pictures.',id:'genai'}],
    deeper:'Training teaches the model to remove noise from images a little at a time. To generate, it starts from pure noise and repeatedly denoises, guided by your text prompt, until a coherent image emerges. It’s more stable to train than GANs, which is why it took over.' },

  { id:'dalle', term:'DALL·E', aliases:'', said:'“doll-E”', aliasList:['dall·e','dall-e','dalle','dall e'], status:'Rising',
    oneLiner:'OpenAI’s image generator — type a description, get a picture.',
    analogy:'An illustrator that never sleeps and takes any brief, however weird.',
    example:'“A cat surfing a taco in watercolor” typed into DALL·E returns exactly that.',
    related:[{text:'Generates images using diffusion.',id:'diffusion'},{text:'A text-to-image tool.',id:'texttoimage'},{text:'The image-side sibling of ChatGPT.',id:'chatgpt'}],
    deeper:'DALL·E popularized text-to-image for the public. Under the hood it pairs an understanding of your prompt with a diffusion image generator. The name is a nod to the artist Dalí and the robot WALL·E.' },

  { id:'texttoimage', term:'Text-to-image', aliases:'', said:'', aliasList:['text-to-image','text to image'], status:'Core',
    oneLiner:'AI that turns a written description into a picture.',
    analogy:'Commissioning art by describing it in words instead of picking up a brush.',
    example:'Typing “a cozy cabin in the snow at dusk” and getting a finished illustration is text-to-image.',
    related:[{text:'Most tools generate the image with diffusion.',id:'diffusion'},{text:'DALL·E is a well-known example.',id:'dalle'},{text:'The visual branch of generative AI.',id:'genai'}],
    deeper:'The model links the meaning of your words to visual patterns learned from millions of caption–image pairs, then generates a matching picture. Quality hinges on the prompt and the training data — which is also where copyright and bias questions get sharp.' },

  { id:'parameters', term:'Parameters', aliases:'Weights', said:'', aliasList:['parameter','parameters','weights'], status:'Core',
    oneLiner:'The millions or billions of internal numbers a model tunes during training — roughly, its stored knowledge.',
    analogy:'The dials on that giant dimmer panel; “175 billion parameters” means 175 billion dials.',
    example:'When people say a model is “bigger,” they usually mean it has more parameters.',
    related:[{text:'They live inside the neural network.',id:'neuralnetwork'},{text:'Setting them is what training does.',id:'trainingdata'},{text:'Fine-tuning nudges a subset of them.',id:'finetuning'}],
    deeper:'Each parameter is a number the model adjusts to reduce its errors during training. More parameters give more capacity to store patterns, which is why counts ballooned into the billions — though size isn’t everything; data quality and training method matter just as much.' },

  { id:'trainingdata', term:'Training data', aliases:'Dataset', said:'', aliasList:['training data','training set','training dataset','dataset','datasets'], status:'Core',
    oneLiner:'The pile of examples a model learns from — its entire education, for better and worse.',
    analogy:'The books, images, and notes you’d hand a student before an exam; whatever’s missing, they won’t know.',
    example:'A model trained mostly on English text will be shakier in Swahili — the training data shaped it.',
    related:[{text:'Learning from it sets the model’s parameters.',id:'parameters'},{text:'Its gaps and slants drive hallucinations.',id:'hallucination'},{text:'The learning step itself is machine learning.',id:'machinelearning'}],
    deeper:'Models don’t memorize their training data so much as absorb its patterns — but its blind spots, biases, and errors get absorbed too. This is why “what was it trained on?” is often the most important question about any AI, and why data quality beats raw quantity.' },

  { id:'inference', term:'Inference', aliases:'', said:'', aliasList:['inference'], status:'Core',
    oneLiner:'The model actually running — doing the work of answering, as opposed to being trained.',
    analogy:'Training is studying for the test; inference is sitting the exam.',
    example:'Every time you send a chatbot a message, you’re paying for a moment of inference.',
    related:[{text:'The opposite phase from training.',id:'trainingdata'},{text:'Its speed and cost are counted in tokens.',id:'tokens'},{text:'Reasoning models spend more compute here for better answers.',id:'reasoningmodels'}],
    deeper:'A model’s life has two phases: training (expensive, done once, sets the parameters) and inference (cheap per run, done constantly, generates outputs). Most of a deployed model’s ongoing cost is inference, which is why speeding it up is a whole industry.' },

  { id:'supervised', term:'Supervised learning', aliases:'', said:'', aliasList:['supervised learning','supervised'], status:'Core',
    oneLiner:'Teaching a model with labeled examples — each input paired with the right answer.',
    analogy:'Flashcards with the answer on the back; the model checks itself against the label.',
    example:'Show a model thousands of emails tagged “spam” or “not spam” and it learns to sort new ones.',
    related:[{text:'The most common form of machine learning.',id:'machinelearning'},{text:'Contrast with unsupervised learning, which has no labels.',id:'unsupervised'},{text:'Labels are part of the training data.',id:'trainingdata'}],
    deeper:'The model makes a guess, compares it to the known label, and adjusts to close the gap — repeated across the dataset. It’s powerful but needs labeled data, which is often expensive to produce; that cost is why other approaches exist.' },

  { id:'unsupervised', term:'Unsupervised learning', aliases:'', said:'', aliasList:['unsupervised learning','unsupervised'], status:'Core',
    oneLiner:'Letting a model find patterns in data on its own, with no answer key.',
    analogy:'Handing someone a box of mixed photos and asking them to sort into groups — without telling them the categories.',
    example:'Grouping customers into “types” nobody defined in advance is unsupervised learning.',
    related:[{text:'Contrast with supervised learning, which uses labels.',id:'supervised'},{text:'Language models pre-train this way on raw text.',id:'pretraining'},{text:'Embeddings often come out of it.',id:'embeddings'}],
    deeper:'With no labels to match, the model organizes data by similarity and structure alone — clustering, compressing, or predicting missing pieces. Modern LLMs lean on a version of this: predicting the next word in raw text is a self-labeling task that needs no human annotation.' },

  { id:'reinforcementlearning', term:'Reinforcement learning', aliases:'RL', said:'', aliasList:['reinforcement learning','rl'], status:'Core',
    oneLiner:'Training by trial and error, with rewards for good moves and penalties for bad ones.',
    analogy:'Training a dog with treats — the model repeats what gets rewarded.',
    example:'AIs that master chess or Go by playing millions of games against themselves use reinforcement learning.',
    related:[{text:'Tuning chatbots with human ratings is RLHF.',id:'rlhf'},{text:'A third path beside supervised and unsupervised learning.',id:'supervised'},{text:'Used to train agents that take actions.',id:'agents'}],
    deeper:'The model acts, gets a reward signal, and adjusts to earn more reward over time — no labeled answers required, just a goal to optimize. It shines where “correct” is hard to label but easy to score, like games, robotics, and, increasingly, aligning language models.' },

  { id:'rlhf', term:'RLHF', aliases:'Reinforcement Learning from Human Feedback', said:'“R-L-H-F”', aliasList:['rlhf','reinforcement learning from human feedback'], status:'Core',
    oneLiner:'Polishing a raw language model with human ratings so it becomes helpful, honest, and easy to talk to.',
    analogy:'After the model learns to talk, people grade its answers and it learns to prefer the ones humans liked.',
    example:'RLHF is a big reason ChatGPT feels cooperative instead of just autocompleting your sentence.',
    related:[{text:'A form of reinforcement learning.',id:'reinforcementlearning'},{text:'Applied on top of a pre-trained model.',id:'pretraining'},{text:'What turned GPT into ChatGPT.',id:'chatgpt'}],
    deeper:'Humans rank competing model answers; those rankings train a “reward model,” which then guides the language model to produce more of what people prefer. It’s the step that aligns a knowledgeable-but-unruly base model with what users actually want — and where much of the “personality” gets set.' },

  { id:'overfitting', term:'Overfitting', aliases:'', said:'', aliasList:['overfitting','overfit'], status:'Core',
    oneLiner:'When a model memorizes its training examples instead of learning the general pattern — acing practice, flunking real life.',
    analogy:'A student who memorized the practice test word-for-word and freezes when the real questions differ.',
    example:'A model that’s perfect on training data but wrong on anything new has overfit.',
    related:[{text:'Caught by testing on held-out data during evals.',id:'evals'},{text:'A risk baked into the training-data step.',id:'trainingdata'},{text:'More parameters can worsen it without enough data.',id:'parameters'}],
    deeper:'Overfitting means the model latched onto noise and quirks specific to the training set rather than the underlying pattern. You detect it by checking performance on data the model never saw; the gap between training and test accuracy is the tell.' },

  { id:'backprop', term:'Backpropagation', aliases:'Backprop', said:'', aliasList:['backpropagation','backprop','back-propagation'], status:'Core',
    oneLiner:'The core algorithm that lets a neural network learn — it traces each mistake backward and nudges every dial to do better.',
    analogy:'After a wrong answer, walking back through the chain to assign a little blame to each step, then correcting each one.',
    example:'Every time a deep learning model improves during training, backpropagation is doing the adjusting.',
    related:[{text:'The learning engine inside a neural network.',id:'neuralnetwork'},{text:'What it tunes are the parameters.',id:'parameters'},{text:'Repeated over the training data.',id:'trainingdata'}],
    deeper:'It works out how much each parameter contributed to the error, then shifts each one slightly to reduce it — repeated millions of times. Conceptually simple and decades old, it’s the quiet workhorse that makes training deep networks possible at all.' },

  { id:'pretraining', term:'Pretraining', aliases:'Pre-training', said:'', aliasList:['pretraining','pre-training','pretrained','pre-trained'], status:'Core',
    oneLiner:'The first, huge phase of learning where a model reads mountains of raw data to build general knowledge — before any fine-tuning.',
    analogy:'A broad general education, before specializing in a job.',
    example:'The “P” in GPT is pre-trained: it read much of the internet before it was ever tuned to chat.',
    related:[{text:'Specializing afterward is fine-tuning.',id:'finetuning'},{text:'Aligning it with human ratings is RLHF.',id:'rlhf'},{text:'Usually done unsupervised on raw text.',id:'unsupervised'}],
    deeper:'Pretraining is where the expensive, general learning happens — predicting the next token across trillions of words builds broad competence. Later, cheaper steps (fine-tuning, RLHF) specialize and align that base. This “pretrain then adapt” recipe is the backbone of modern AI.' },

  { id:'foundationmodel', term:'Foundation model', aliases:'', said:'', aliasList:['foundation model','foundation models'], status:'Core',
    oneLiner:'A big, general model trained once on broad data, then adapted for many different tasks.',
    analogy:'A versatile base ingredient — like flour — that lots of specific dishes get built from.',
    example:'GPT-4 is a foundation model: the same base powers chat, coding help, and dozens of apps.',
    related:[{text:'For text, it’s usually a large language model.',id:'llm'},{text:'Adapting one to your task is fine-tuning.',id:'finetuning'},{text:'Its broad skills come from pretraining.',id:'pretraining'}],
    deeper:'The term captures a shift: instead of training a fresh model per task, you build one large, general model and adapt it many ways. That reuse is why a handful of expensive foundation models now sit under thousands of products.' },

  { id:'multimodal', term:'Multimodal', aliases:'', said:'', aliasList:['multimodal','multi-modal','multimodality'], status:'Rising',
    oneLiner:'AI that handles more than one kind of input or output — text, images, audio, video — in a single model.',
    analogy:'A worker who can read, look at pictures, and listen, instead of only reading.',
    example:'Snap a photo of your fridge and ask “what can I cook?” — a multimodal model reads the image and replies in text.',
    related:[{text:'Extends a large language model beyond text.',id:'llm'},{text:'Text-to-image is one multimodal pairing.',id:'texttoimage'},{text:'Lets agents use screenshots for computer use.',id:'computeruse'}],
    deeper:'A multimodal model maps different data types into a shared representation so it can reason across them — describe an image, answer questions about a chart, or caption a video. It’s where the frontier models are heading, since most real tasks mix formats.' },
];

window.DECODER_LENSES = {
  rag:{ pm:'Ground the bot in your own docs so answers cite real sources — fewer escalations, no invented policies.', eng:'Retrieve top-k relevant chunks via vector search and inject them into the prompt at inference time.' },
  evals:{ pm:'A regression suite for quality — proof a change actually moved the metric before you ship.', eng:'Automated graders (exact-match, rubric, or LLM-as-judge) scoring output over a fixed dataset.' },
  contextwindow:{ pm:"The model's attention budget — overload it and details drop, so scope what you feed it.", eng:'Max token span the model attends over; content beyond it is truncated or must be chunked/retrieved.' },
  hitl:{ pm:'A human approval gate on risky actions — your control point for compliance and trust.', eng:'An approval checkpoint that blocks an action until a human confirms (all / sampled / low-confidence).' },
  agents:{ pm:'AI that completes multi-step tasks end to end — automation you delegate outcomes to, not just answers.', eng:'A model-driven loop: choose action → run tool → observe result → repeat until a stop condition.' },
  embeddings:{ pm:"The tech behind 'find similar' — powers semantic search, dedup, and recommendations.", eng:'Dense vector representations where cosine distance approximates semantic similarity.' },
  finetuning:{ pm:'Teaching the model your style with examples — powerful but a maintenance cost; try prompting/RAG first.', eng:'Gradient updates on a base model (often LoRA/PEFT) over labeled examples to shift behavior.' },
  vibecoding:{ pm:'The 2024 name for prompt-until-it-works prototyping — now matured into agentic coding with guardrails.', eng:'Prompt-driven codegen without close review; superseded by agent workflows with tests and specs.' },
  promptengineering:{ pm:'Wording requests well for better output — a fading standalone skill as models read intent better.', eng:'Structuring prompts (instructions, examples, format constraints) to steer the output distribution.' },
  tokens:{ pm:'The billing and length unit for AI — costs and limits are counted in these, not words.', eng:'Sub-word units from the tokenizer; model I/O and pricing are both measured per token.' },
  hallucination:{ pm:'Confident wrong answers — the core reliability risk; mitigate with grounding, citations, and evals.', eng:'Plausible-but-false generations from likelihood-based decoding untethered from ground truth.' },
  mcp:{ pm:'A standard that lets any AI plug into your tools without custom builds — faster integrations, less lock-in.', eng:'An open protocol for tool/data discovery and invocation between a model host and external servers.' },
  chainofthought:{ pm:'Letting the model reason step by step — better accuracy on hard tasks, now built into reasoning models.', eng:'Intermediate reasoning tokens before the answer; boosts multi-step tasks, often internalized in reasoning models.' },
  temperature:{ pm:'A creativity dial — low for reliable extraction, high for brainstorming variety.', eng:'Softmax scaling on next-token logits; higher flattens the distribution, lower sharpens it.' },
  promptinjection:{ pm:'A security risk where malicious text hijacks your AI — a key reason to gate agent actions.', eng:'Adversarial instructions in untrusted input the model executes; mitigate via isolation + approval, not solved.' },
  contextengineering:{ pm:'The discipline of feeding the model the right information at each step — usually the real lever behind a “smarter” agent.', eng:'Runtime assembly of LLM input (instructions, retrieved chunks, history, tool outputs) under token and ordering constraints.' },
  orchestration:{ pm:'The engine that turns a model into a multi-step agent — where reliability and control actually live.', eng:'The loop/state machine coordinating model calls, tool invocation, memory, and stop conditions.' },
  tooluse:{ pm:'What lets an agent take real actions — the difference between an assistant that answers and one that does.', eng:'Model emits schema-conformant call requests; the runtime executes and returns results into context.' },
  a2a:{ pm:'An emerging standard for agents built by different teams to interoperate — less custom glue, more reuse.', eng:'Open protocol: Agent Cards for discovery, task-oriented async messaging with streaming updates.' },
  llmjudge:{ pm:'A way to measure fuzzy quality at scale — proof a change helped, without hand-grading everything.', eng:'A grader model scores outputs against a rubric over a fixed eval set; validate against human labels.' },
  grounding:{ pm:'Anchoring answers in your real sources — the biggest lever for trust and fewer wrong answers.', eng:'Injecting retrieved authoritative data into context so generations are traceable to sources.' },
  multiagent:{ pm:'A team of specialist agents over one do-everything agent — better for complex, multi-part work.', eng:'Decomposed task handled by specialized agents via coordinator/sequential/critic patterns.' },
  agentops:{ pm:'The operational discipline that keeps an agent reliable after launch — where most of the real work lives.', eng:'Continuous eval, tracing, and metrics gating deploys; failures become regression cases.' },
  guardrails:{ pm:'The safety limits that let you trust an agent with real actions — your compliance and risk control.', eng:'Deterministic policy checks plus guard models wrapping tool calls and I/O; least privilege.' },
  observability:{ pm:'Being able to see inside an agent’s decisions — the difference between debugging and guessing.', eng:'Logs, traces (per-run trajectory), and metrics; OpenTelemetry-style spans over the agent loop.' },
  agentmemory:{ pm:'What makes an agent feel personal and continuous instead of forgetting you every session.', eng:'Short-term session state plus long-term store (usually vector-backed) with write/retrieve tools.' },
  react:{ pm:'The think-act-observe rhythm behind agents that tackle a task step by step.', eng:'Interleaved reasoning + tool actions with observations fed back before the next step.' },
  computeruse:{ pm:'Automation for systems with no API — flexible, but slower and riskier than a real integration.', eng:'Vision-driven UI control (screenshot → click/type) over an app’s interface; brittle, needs oversight.' },
  agentidentity:{ pm:'Treating each agent as its own accountable actor — the key to safe delegation at scale.', eng:'Per-agent cryptographic identity (e.g., SPIFFE) with least-privilege IAM and audit trails.' },
  vectordb:{ pm:'The tech that powers “find similar” over your content — foundation for search, RAG, and memory.', eng:'Indexes embeddings for approximate nearest-neighbor lookup (cosine/dot) at scale.' },
  agentpayments:{ pm:'The nascent rails for agents to spend money safely — mostly a “watch this space” for now.', eng:'AP2 signed intent mandates + x402 (HTTP 402) micropayments; early, non-standardized.' },
  reasoningmodels:{ pm:'Models that trade speed and cost for accuracy on hard, multi-step problems.', eng:'Models trained to emit extended internal reasoning tokens before the answer; higher latency/cost.' },
  trajectory:{ pm:'Judging how an agent got there, not just whether the answer was right — key to real quality.', eng:'The ordered sequence of reasoning/tool/observation steps; unit of trajectory (glass-box) evaluation.' },
  genai:{ pm:'The category your product bets on — new content on demand; the question is where it adds value vs. novelty.', eng:'Models that sample new outputs from a learned distribution (LLMs, diffusion) rather than classify existing inputs.' },
  machinelearning:{ pm:'Software that improves from data instead of hand-written rules — plan for data collection and retraining.', eng:'Algorithms that fit parameters to data to minimize a loss and generalize to unseen inputs.' },
  deeplearning:{ pm:'The approach behind modern AI capabilities — powerful, but data- and compute-hungry to build.', eng:'Multi-layer neural networks trained via backprop; scales with data and GPU compute.' },
  neuralnetwork:{ pm:'The building block under most AI features — the learned model you ship and monitor.', eng:'Layered weighted units with nonlinearities; parameters fit by gradient descent.' },
  prompt:{ pm:'The user-facing input that steers output quality — often your cheapest lever before any model change.', eng:'The full input string (instructions, examples, context) conditioning next-token generation.' },
  llm:{ pm:'The core engine for text features — capable but probabilistic; design for review and failure modes.', eng:'Transformer trained on next-token prediction over large corpora; autoregressive decoding.' },
  transformer:{ pm:'The architecture that unlocked today’s AI — mostly a build detail, but the reason capabilities jumped.', eng:'Attention-based architecture enabling parallel sequence modeling; basis of modern LLMs.' },
  gpt:{ pm:'A leading model family to benchmark against — track versions for capability and cost shifts.', eng:'OpenAI decoder-only transformer line; scaling parameters/data across generations.' },
  chatgpt:{ pm:'The product that set user expectations for AI chat — your baseline for UX and quality comparisons.', eng:'Chat app over a GPT model, instruction-tuned with RLHF for dialogue.' },
  gan:{ pm:'Legacy image-gen tech — mostly relevant for context; new work uses diffusion.', eng:'Generator vs. discriminator adversarial training; largely superseded by diffusion for image synthesis.' },
  diffusion:{ pm:'The engine behind AI image features — plan for latency, safety filtering, and content rights.', eng:'Iterative denoising from noise conditioned on a prompt; stable to train, sampling-step heavy.' },
  dalle:{ pm:'A reference text-to-image product — useful for competitive and UX benchmarking.', eng:'Prompt-conditioned diffusion image generator (OpenAI).' },
  texttoimage:{ pm:'A feature pattern — describe, generate, iterate; watch prompt UX and rights/safety.', eng:'Prompt-conditioned image generation trained on caption–image pairs, typically diffusion-based.' },
  parameters:{ pm:'A rough proxy for model size, cost, and capability — bigger isn’t automatically better.', eng:'Learned weights; count indicates capacity but data/method drive quality.' },
  trainingdata:{ pm:'The single biggest driver of behavior and bias — “what’s it trained on?” is a product-risk question.', eng:'Corpus fit during training; distribution and quality bound model behavior and failure modes.' },
  inference:{ pm:'The recurring per-use cost of AI features — the number that scales with adoption.', eng:'Forward-pass generation at serving time; dominant ongoing cost, latency-sensitive.' },
  supervised:{ pm:'Reliable when you can label data — budget for the labeling effort.', eng:'Learning input→label mappings by minimizing loss against ground-truth labels.' },
  unsupervised:{ pm:'Finds structure without labels — good for discovery, fuzzier to evaluate.', eng:'Learning structure from unlabeled data (clustering, self-supervised objectives).' },
  reinforcementlearning:{ pm:'Best when success is scorable but not labelable — powerful for optimization and agents.', eng:'Policy learning from reward signals via trial and error to maximize return.' },
  rlhf:{ pm:'The step that makes models feel helpful and on-brand — where alignment and tone get set.', eng:'Reward model from human preference rankings guides policy optimization of the base model.' },
  overfitting:{ pm:'The reason a model looks great in the demo and fails in production — insist on held-out evals.', eng:'Low training error, high generalization error; fit to noise rather than signal.' },
  backprop:{ pm:'A training internal — matters as the mechanism that makes learning (and its cost) possible.', eng:'Gradient computation via the chain rule to update weights; core of neural-network training.' },
  pretraining:{ pm:'The expensive, general phase you usually buy rather than build — you adapt on top of it.', eng:'Large-scale self-supervised training that builds general capability before task adaptation.' },
  foundationmodel:{ pm:'Buy-vs-build pivot: adapt one general model across features instead of training per task.', eng:'Broadly pretrained model adapted (prompting/fine-tuning) to many downstream tasks.' },
  multimodal:{ pm:'Unlocks features that mix text, images, and audio — expands use cases and evaluation surface.', eng:'Shared representations across modalities enabling cross-modal input/output.' },
};

window.DECODER_STATUS = {
  Core:       { label:'Core',       sym:'●', color:'oklch(0.5 0.085 155)', bg:'oklch(0.955 0.03 155)' },
  Rising:     { label:'Rising',     sym:'▲', color:'oklch(0.56 0.12 55)',  bg:'oklch(0.955 0.05 72)'  },
  Fading:     { label:'Fading',     sym:'▼', color:'oklch(0.55 0.05 250)', bg:'oklch(0.955 0.022 250)'},
  Historical: { label:'Historical', sym:'†', color:'oklch(0.5 0 0)',       bg:'oklch(0.925 0 0)'      },
};
