-- Decoder — content batch 001 (4 terms). Generated; idempotent upsert.
insert into public.concepts
  (id, term, aliases, said, alias_list, status, one_liner, analogy, example, related, deeper, lens_pm, lens_eng, domain, priority, tags)
values
  ('vectordatabase', 'Vector database', '', '', ARRAY['vector database','vector db','vector store']::text[], 'Core', 'A database built to store meanings as coordinates and find the nearest ones fast — the memory bank behind RAG.', 'A library shelved by what books are about, not by title — so “nearby” means “similar in meaning.”', 'Ask a support bot a question and it pulls the three closest help-doc chunks from a vector database.', '[{"text":"Stores the embeddings that power retrieval.","id":"embeddings"},{"text":"The lookup step inside RAG.","id":"rag"}]'::jsonb, 'It indexes high-dimensional vectors and answers “what’s closest to this?” in milliseconds using approximate nearest-neighbor search. Exact search is too slow at scale, so it trades a sliver of accuracy for big speed. The index structure (like HNSW) is what makes that trade work.', 'The storage layer that makes semantic search and RAG feasible at scale.', 'An ANN index over embedding vectors supporting top-k similarity queries with metadata filters.', 'Retrieval & memory', 80, ARRAY['seed','retrieval-memory']::text[]),
  ('reranking', 'Reranking', '', '', ARRAY['reranking','reranker','re-rank']::text[], 'Rising', 'A second-pass sort that takes the retriever’s rough shortlist and reorders it by who actually answers the question best.', 'A hiring manager reading the résumés that HR’s keyword filter already passed through.', 'Retrieve 50 candidate chunks cheaply, then rerank to keep the 5 that truly fit before answering.', '[{"text":"Cleans up what retrieval hands over.","id":"retrieval"},{"text":"A quality lever for RAG.","id":"rag"}]'::jsonb, 'Fast retrieval favors recall — cast a wide net — but the top hits aren’t always the most relevant. A reranker (often a heavier cross-encoder that reads query and chunk together) scores each candidate directly, catching the good ones the first pass buried. More compute, better precision.', 'A cheap accuracy boost for RAG: keep retrieval wide, then let reranking pick the winners.', 'A cross-encoder scoring (query, passage) pairs to reorder first-stage retrieval by relevance.', 'Retrieval & memory', 60, ARRAY['seed','retrieval-memory']::text[]),
  ('retrieval', 'Retrieval', '', '', ARRAY['retrieval','retriever']::text[], 'Core', 'The step that goes and finds the right supporting text before the model answers — the “R” in RAG.', 'Sending a runner to the archive to fetch the relevant files before the meeting starts.', 'You ask about refund policy; retrieval grabs the refund section from the docs to hand the model.', '[{"text":"The engine of RAG.","id":"rag"},{"text":"Searches over embeddings.","id":"embeddings"},{"text":"Often cleaned up by reranking.","id":"reranking"}]'::jsonb, 'Retrieval turns your question into a query, searches an index, and returns the closest matches. It can be semantic (embedding similarity), lexical (keyword/BM25), or hybrid. Everything downstream depends on it — the model can only reason over what retrieval actually fetched.', 'Get this right and answers stay grounded; get it wrong and no model can save the response.', 'Query-to-index matching (dense, sparse, or hybrid) returning top-k context for generation.', 'Retrieval & memory', 80, ARRAY['seed','retrieval-memory']::text[]),
  ('chunking', 'Chunking', '', '', ARRAY['chunking','chunk','chunk overlap']::text[], 'Core', 'Slicing long documents into bite-size passages so retrieval can fetch just the relevant piece, not the whole file.', 'Cutting a book into index cards so you can pull the one paragraph you need.', 'A 40-page manual gets split into ~300-word chunks, each embedded and searchable on its own.', '[{"text":"Prepares documents for retrieval.","id":"retrieval"},{"text":"Each chunk becomes an embedding.","id":"embeddings"}]'::jsonb, 'Chunk too big and retrieval drags in irrelevant text that dilutes the answer; too small and you sever the context a passage needs to make sense. A little overlap between chunks keeps ideas from being cut mid-thought. It’s unglamorous, but chunking quality quietly decides RAG quality.', 'A boring knob with outsized impact on answer quality — worth tuning early.', 'Segmenting docs into overlapping passages sized for the embedding model and context budget.', 'Retrieval & memory', 80, ARRAY['seed','retrieval-memory']::text[])
on conflict (id) do update set
  term=excluded.term, aliases=excluded.aliases, said=excluded.said, alias_list=excluded.alias_list,
  status=excluded.status, one_liner=excluded.one_liner, analogy=excluded.analogy, example=excluded.example,
  related=excluded.related, deeper=excluded.deeper, lens_pm=excluded.lens_pm, lens_eng=excluded.lens_eng,
  domain=excluded.domain, priority=excluded.priority, tags=excluded.tags, updated_at=now();
